using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShoppinCartApp.DataAccess.Models
{
    [Table("Addresses")]
    public class Address
    {
        /// <summary>
        /// Address entity
        /// </summary>
        [Key]
        [Column("Id")] //autogenerated
        public int AddressId { get; set; }
        [Required]
        [DataType("varchar")]
        [Column("FullAddress")]
        [MaxLength(100, ErrorMessage = "Name cannot me more than 100 characters. Consider adding shortform")]
        public string UserAddress { get; set; }
        [ForeignKey("User")]
        public int? UserId { get; set; } //adding foreign key from user table //make sure it's non nullable
        public virtual User? User { get; set; }
    }
}
