using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShoppinCartApp.DataAccess.Models
{
    [Table("Users")]
    public class User
    {
        /// <summary>
        /// user entity
        /// </summary>
        [Key]
        [Column("Id")]
        public int UserId { get; set; } //autogenerated
        [Required]
        [DataType("varchar")]
        [Column("FirstName")]
        [MaxLength(30, ErrorMessage = " Consider adding short names")]
        public string UserFName { get; set; }
        [DataType("varchar")]
        [Column("LastName")]
        [MaxLength(30, ErrorMessage = " Consider adding short names")]
        public string? UserLName { get; set; }
        [Required]
        [DataType("varchar")]
        [Column("Contact")]
        [MaxLength(10)]
        public string UserContact { get; set; }
        [Required]
        [DataType("varchar")]
        [Column("EmailID")]
        [MaxLength(254)]
        public string UserEmail { get; set; }
    }
}
